apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: v3m-alfresco-cms-api
  resources:
    requests:
      storage: 4Gi