apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    name: postgres
    app: v3md-alfresco
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: v3m-alfresco-cms-api
  resources:
    requests:
      storage: 4Gi