kind: Deployment
apiVersion: apps/v1
metadata:
  name: activemq
  namespace: v3md-alfresco
  selfLink: /apis/apps/v1/namespaces/v3md-alfresco/deployments/activemq
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: 'alfresco/alfresco-activemq:5.15.8'
          ports:
            - containerPort: 8161
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 61616
              protocol: TCP
            - containerPort: 61613
              protocol: TCP