kind: Deployment
apiVersion: apps/v1
metadata:
  name: v3md-alfresco
  namespace: v3md-alfresco
  selfLink: /apis/apps/v1/namespaces/v3md-alfresco/deployments/v3md-alfresco
  labels:
    k8s-app: v3md-alfresco
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: v3md-alfresco
  template:
    metadata:
      name: v3md-alfresco
      labels:
        k8s-app: v3md-alfresco
    spec:
      containers:
        - name: v3md-alfresco
          image: 'v3md/acs-community-packaging:v3macscmsC10'
          env:
            - name: JAVA_OPTS
              value: >-
                -Ddb.driver=org.postgresql.Driver -Ddb.username=alfresco
                -Ddb.password=alfresco            
                -Ddb.url=jdbc:postgresql://10.99.124.87:5432/alfresco
                -Dsolr.host=10.105.113.120 -Dsolr.port=8083            
                -Dsolr.secureComms=none -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6             -Dshare.host=172.17.0.2
                -Dshare.port=31786 -Dalfresco.host=localhost
                -Dalfresco.port=8080            
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url="failover:(nio://10.100.38.3:61616)?timeout=3000&jms.useCompression=true"            
                -Ddeployment.method=DOCKER_COMPOSE
                -DlocalTransform.core-aio.url=http://10.108.79.96:8090/            
                -Dalfresco-pdf-renderer.url=http://10.108.79.96:8090/
                -Djodconverter.url=http://10.108.79.96:8090/            
                -Dimg.url=http://10.108.79.96:8090/
                -Dtika.url=http://10.108.79.96:8090/            
                -Dtransform.misc.url=http://10.108.79.96:8090/
                -Dcsrf.filter.enabled=false -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80 -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
      imagePullSecrets:
        - name: regcred
