apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: v3md-alfresco
  selfLink: /apis/apps/v1/namespaces/v3md-alfresco/deployments/postgres
  labels:
    name: postgres
    app: v3md-alfresco
spec:
  selector:
    matchLabels:
      name: postgres
      app: v3md-alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: postgres
        app: v3md-alfresco
    spec:
      containers:
        - name: postgres
          image: postgres:11.7
          env:
            - name: POSTGRES_USER
              value: alfresco
            - name: POSTGRES_PASSWORD
              value: alfresco
            - name: POSTGRES_DB
              value: alfresco
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-pv-claim