apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.7
          env:
            - name: POSTGRES_USER
              value: alfresco
            - name: POSTGRES_PASSWORD
              value: alfresco
            - name: POSTGRES_DB
              value: alfresco
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-pv-claim