kind: Deployment
apiVersion: apps/v1
metadata:
  name: share
  namespace: v3md-alfresco
  selfLink: /apis/apps/v1/namespaces/v3md-alfresco/deployments/share
  labels:
    io.kompose.service: share
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: share
  template:
    metadata:
      labels:
        io.kompose.service: share
    spec:
      containers:
        - name: share
          image: 'alfresco/alfresco-share:6.2.1'
          env:
            - name: JAVA_OPTS
              value: ' -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80 -Dalfresco.host=10.101.63.5 -Dalfresco.port=8080 -Dalfresco.context=alfresco -Dalfresco.protocol=http '
            - name: REPO_HOST
              value: 10.101.63.5
            - name: REPO_PORT
              value: '8080'
