kind: Deployment
apiVersion: apps/v1
metadata:
  name: solr6
  namespace: v3md-alfresco
  selfLink: /apis/apps/v1/namespaces/v3md-alfresco/deployments/solr6
  labels:
   app: solr6
spec:
  replicas: 1
  selector:
    matchLabels:
     app: solr6
  template:
    metadata:
      labels:
       app: solr6
    spec:
      containers:
        - name: solr6
          image: 'alfresco/alfresco-search-services:2.0.0'
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 8983
              protocol: TCP
          env:
            - name: ALFRESCO_SECURE_COMMS
              value: none
            - name: SOLR_ALFRESCO_HOST
              value: 10.101.63.5
            - name: SOLR_ALFRESCO_PORT
              value: '8080'
            - name: SOLR_CREATE_ALFRESCO_DEFAULTS
              value: 'alfresco,archive'
            - name: SOLR_SOLR_HOST
              value: localhost
            - name: SOLR_SOLR_PORT
              value: '8983'
          volumeMounts:
            - mountPath: /opt/alfresco-search-services/data
              name: solr6
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
        - hostPath:
            path: /opt/alfresco-search-services/data
            type: ""
          name: solr6