kind: Deployment
apiVersion: apps/v1
metadata:
  name: transform-core-aio
  namespace: v3md-alfresco
  selfLink: /apis/apps/v1/namespaces/v3md-alfresco/deployments/transform-core-aio
  labels:
    app: v3md-alfresco
    name: transform-core-aio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v3md-alfresco
      name: transform-core-aio
  template:
    metadata:
      labels:
        app: v3md-alfresco
        name: transform-core-aio
    spec:
      containers:
        - name: transform-core-aio
          image: 'alfresco/alfresco-transform-core-aio:2.3.6'
          ports:
            - containerPort: 8090
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: ' -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80'
