kind: Deployment
apiVersion: apps/v1
metadata:
  name: transform-core-aio
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/transform-core-aio
  labels:
    io.kompose.service: transform-core-aio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transform-core-aio
  template:
    metadata:
      labels:
        io.kompose.service: transform-core-aio
    spec:
      containers:
        - name: transform-core-aio
          image: 'alfresco/alfresco-transform-core-aio:2.3.6'
          ports:
            - containerPort: 8090
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: ' -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80'
